/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Computer.glb -T 
Files: Computer.glb [21.62MB] > D:\Escritorio\3d-portfolio-main\3d-portfolio-main\public\models\Computer-transformed.glb [10.14MB] (53%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Computer (props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/Computer-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="RootNode" scale={0.01}>
          <group name="MAINPYRAMID" position={[4.715, 8.828, 72.886]}>
            <group name="BATTERY" position={[11.589, 55.194, 101.184]} rotation={[0, -0.986, 0]}>
              <group name="Mesh" position={[-153.35, -19.265, 36.312]} rotation={[0, -0.334, 0]}>
                <mesh name="Mesh_BASE_0" geometry={nodes.Mesh_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="Mesh_1" position={[-126.87, -19.265, 47.297]} rotation={[0, 0.722, 0]}>
                <mesh name="Mesh_1_BASE_0" geometry={nodes.Mesh_1_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="Mesh_2" position={[-132.953, 0, 38.705]} rotation={[0, -0.556, 0]}>
                <mesh name="Mesh_2_BASE_0" geometry={nodes.Mesh_2_BASE_0.geometry} material={materials.BASE} />
              </group>
            </group>
            <group name="BOOKS" position={[43.172, 26.515, 84.656]} rotation={[-Math.PI / 2, 0, 2]} scale={100}>
              <group name="BooksHorizontal" position={[-0.039, 0, 0]}>
                <mesh name="BooksHorizontal_BASE_0" geometry={nodes.BooksHorizontal_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="BooksHorizontal_1" position={[-0.644, -0.136, 0]} rotation={[0, 0, 1.545]}>
                <mesh name="BooksHorizontal_1_BASE_0" geometry={nodes.BooksHorizontal_1_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="BooksVertical" position={[-0.256, 0, 0]}>
                <mesh name="BooksVertical_BASE_0" geometry={nodes.BooksVertical_BASE_0.geometry} material={materials.BASE} />
              </group>
            </group>
            <group name="Gramophone" position={[7.878, 20.075, 82.142]} rotation={[0, 0.505, 0]}>
              <group name="Cylinder_2" position={[0.545, 28.281, -0.478]} rotation={[0.035, 0, 0]} scale={[5.521, 0.147, 5.521]}>
                <mesh name="Cylinder_2_BASE_0" geometry={nodes.Cylinder_2_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="pCube1" position={[0, 9.769, 0]} scale={[12.351, 0.451, 17.596]}>
                <mesh name="pCube1_BASE_0" geometry={nodes.pCube1_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="pCube2" position={[-19.75, 23.475, 2.001]} scale={[1.018, 1.123, 0.304]}>
                <mesh name="pCube2_BASE_0" geometry={nodes.pCube2_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="pCylinder1" position={[-22.746, 40.309, 0.886]} rotation={[0, -0.231, 0]} scale={[1.132, 0.652, 1.132]}>
                <mesh name="pCylinder1_kette_0" geometry={nodes.pCylinder1_kette_0.geometry} material={materials.kette} />
              </group>
              <group name="pCylinder12" position={[45.778, -12.532, 16.994]} rotation={[0, -0.231, Math.PI / 2]}>
                <mesh name="pCylinder12_BASE_0" geometry={nodes.pCylinder12_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="pTorus1" position={[-22.446, 38.302, 1.33]} scale={[2.092, 1.631, 2.363]}>
                <mesh name="pTorus1_BASE_0" geometry={nodes.pTorus1_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="ROBOT" position={[9.69, 36.497, -5.446]} rotation={[0, 0.3, 0]}>
                <group name="Object_130">
                  <group name="IK_Stopa_L" position={[2.969, -7.777, -3.601]} />
                  <group name="IK_Stopa_R" position={[-2.969, -7.777, 0.099]} />
                  <group name="L_Foot_CTRL" position={[0, 0, -3.7]} />
                  <group name="Osnova_CTRL" position={[0, -0.6, 0]}>
                    <group name="Top_CTRL">
                      <group name="Objective_Vnesh_CTRL" />
                      <group name="Objective_Vnutr_CTRL" />
                    </group>
                  </group>
                  <group name="R_Foot_CTRL" />
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh name="Object_133" geometry={nodes.Object_133.geometry} material={materials.BASE} skeleton={nodes.Object_133.skeleton} />
                  <skinnedMesh name="Object_135" geometry={nodes.Object_135.geometry} material={materials.BASE} skeleton={nodes.Object_135.skeleton} />
                  <skinnedMesh name="Object_137" geometry={nodes.Object_137.geometry} material={materials.BASE} skeleton={nodes.Object_137.skeleton} />
                  <skinnedMesh name="Object_139" geometry={nodes.Object_139.geometry} material={materials.BASE} skeleton={nodes.Object_139.skeleton} />
                  <skinnedMesh name="Object_141" geometry={nodes.Object_141.geometry} material={materials.BASE} skeleton={nodes.Object_141.skeleton} />
                  <skinnedMesh name="Object_143" geometry={nodes.Object_143.geometry} material={materials.BASE} skeleton={nodes.Object_143.skeleton} />
                  <skinnedMesh name="Object_145" geometry={nodes.Object_145.geometry} material={materials.BASE} skeleton={nodes.Object_145.skeleton} />
                  <skinnedMesh name="Object_147" geometry={nodes.Object_147.geometry} material={materials.BASE} skeleton={nodes.Object_147.skeleton} />
                  <skinnedMesh name="Object_149" geometry={nodes.Object_149.geometry} material={materials.BASE} skeleton={nodes.Object_149.skeleton} />
                  <skinnedMesh name="Object_151" geometry={nodes.Object_151.geometry} material={materials.BASE} skeleton={nodes.Object_151.skeleton} />
                  <skinnedMesh name="Object_153" geometry={nodes.Object_153.geometry} material={materials.BASE} skeleton={nodes.Object_153.skeleton} />
                  <skinnedMesh name="Object_155" geometry={nodes.Object_155.geometry} material={materials.BASE} skeleton={nodes.Object_155.skeleton} />
                </group>
              </group>
            </group>
            <group name="LAPTOP" position={[148.936, 32.363, -78.146]} rotation={[Math.PI, -1.051, Math.PI]}>
              <group name="BezierCurve" position={[-10.371, -2.654, -9.784]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="BezierCurve_BASE_0" geometry={nodes.BezierCurve_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="BezierCurve_001" position={[-10.371, -2.4, -9.784]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="BezierCurve_001_BASE_0" geometry={nodes.BezierCurve_001_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="BezierCurve_002" position={[-10.371, -2.842, -9.784]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="BezierCurve_002_BASE_0" geometry={nodes.BezierCurve_002_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="Cube001" position={[0, 6.983, -1.23]} rotation={[-1.943, 0, -Math.PI / 2]} scale={100}>
                <mesh name="Cube_BASE_0" geometry={nodes.Cube_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="Cube_001" position={[0, 6.983, -1.23]} rotation={[-1.943, 0, 0]} scale={100}>
                <mesh name="Cube_001_BASE_0" geometry={nodes.Cube_001_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="Cube_002" position={[0, 6.983, -1.23]} rotation={[-1.943, 0, 0]} scale={100}>
                <mesh name="Cube_002_BASE_0" geometry={nodes.Cube_002_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="Cube_003" position={[0, 6.983, -1.23]} rotation={[-1.943, 0, -Math.PI / 2]} scale={100}>
                <mesh name="Cube_003_BASE_0" geometry={nodes.Cube_003_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="Cube_004" position={[0, -3.542, 1.012]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Cube_004_BASE_0" geometry={nodes.Cube_004_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="Cube_005" position={[0, -3.542, 1.012]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Cube_005_BASE_0" geometry={nodes.Cube_005_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="Cube_006" position={[2.404, -3.542, 1.012]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Cube_006_BASE_0" geometry={nodes.Cube_006_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="Cube_007" position={[0, -5.558, 10.441]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Cube_007_BASE_0" geometry={nodes.Cube_007_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="Cube_012" position={[-12.604, -3.524, 3.15]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Cube_012_BASE_0" geometry={nodes.Cube_012_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="Cube_013" position={[-12.643, -3.972, 0.576]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Cube_013_BASE_0" geometry={nodes.Cube_013_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="Cube_014" position={[-25.22, -3.18, 1.012]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Cube_014_BASE_0" geometry={nodes.Cube_014_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="Cube_015" position={[-25.22, -3.18, 1.012]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Cube_015_BASE_0" geometry={nodes.Cube_015_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="Cube_016" position={[-0.084, -1.646, -7.271]} rotation={[2.55, 0.005, -1.581]} scale={100}>
                <mesh name="Cube_016_BASE_0" geometry={nodes.Cube_016_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="Cube_017" position={[13.93, -3.993, 3.486]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Cube_017_BASE_0" geometry={nodes.Cube_017_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="Cube_018" position={[-8.334, -3.016, -0.796]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Cube_018_BASE_0" geometry={nodes.Cube_018_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="Cube_019" position={[-3.422, -3.016, -0.796]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Cube_019_BASE_0" geometry={nodes.Cube_019_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="Cube_020" position={[0, 6.983, -1.23]} rotation={[-1.943, 0, -Math.PI / 2]} scale={100}>
                <mesh name="Cube_020_BASE_0" geometry={nodes.Cube_020_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="Cylinder_002" position={[-0.484, 0.118, 0.405]} rotation={[-2.049, 0, 0]} scale={100}>
                <mesh name="Cylinder_002_BASE_0" geometry={nodes.Cylinder_002_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="Cylinder_3" position={[1.041, 0.118, 0.405]} rotation={[-2.049, 0, 0]} scale={100}>
                <mesh name="Cylinder_3_BASE_0" geometry={nodes.Cylinder_3_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="Keys" position={[-9.996, -3.831, 4.906]} rotation={[-Math.PI / 2, 0, 0.002]} scale={100}>
                <mesh name="Keys_BASE_0" geometry={nodes.Keys_BASE_0.geometry} material={materials.BASE} />
              </group>
            </group>
            <group name="PERSON" position={[137.819, -26, -126.849]} rotation={[-Math.PI, 1.467, -Math.PI]}>
              <group name="Circle" position={[1.011, 98.586, 10.838]}>
                <group name="Null_4" position={[25, 0, 0]}>
                  <group name="Extrude_9">
                    <mesh name="Extrude_9_BASE_0" geometry={nodes.Extrude_9_BASE_0.geometry} material={materials.BASE} />
                  </group>
                </group>
              </group>
              <group name="Circle_1" position={[1.011, 98.586, 10.838]} rotation={[0, 1.55, 0]}>
                <group name="Null_3" position={[25, 0, 0]} rotation={[-Math.PI, 0, -Math.PI]}>
                  <group name="PENGUIN">
                    <group name="Cylinder_005" position={[-0.074, -2.231, 5.681]}>
                      <mesh name="Cylinder_005_BASE_0" geometry={nodes.Cylinder_005_BASE_0.geometry} material={materials.BASE} />
                    </group>
                    <group name="Arm" position={[-1.682, 0.923, -0.834]}>
                      <mesh name="Arm_BASE_0" geometry={nodes.Arm_BASE_0.geometry} material={materials.BASE} />
                    </group>
                    <group name="Arm2" position={[1.51, 0.922, -0.834]}>
                      <mesh name="Arm2_BASE_0" geometry={nodes.Arm2_BASE_0.geometry} material={materials.BASE} />
                    </group>
                    <group name="Body" position={[-0.094, 0.874, -0.834]}>
                      <mesh name="Body_BASE_0" geometry={nodes.Body_BASE_0.geometry} material={materials.BASE} />
                    </group>
                    <group name="Eyes" position={[0, 1.957, -0.075]}>
                      <mesh name="Eyes_BASE_0" geometry={nodes.Eyes_BASE_0.geometry} material={materials.BASE} />
                    </group>
                    <group name="Foot2" position={[0.525, -1.072, -0.007]}>
                      <mesh name="Foot2_BASE_0" geometry={nodes.Foot2_BASE_0.geometry} material={materials.BASE} />
                    </group>
                    <group name="Nose" position={[-0.02, 1.203, 0.149]}>
                      <mesh name="Nose_BASE_0" geometry={nodes.Nose_BASE_0.geometry} material={materials.BASE} />
                    </group>
                    <group name="Plane_001" position={[-0.074, -2.304, -3.304]}>
                      <mesh name="Plane_001_BASE_0" geometry={nodes.Plane_001_BASE_0.geometry} material={materials.BASE} />
                    </group>
                  </group>
                </group>
              </group>
              <mesh name="PERSON_BASE_0" geometry={nodes.PERSON_BASE_0.geometry} material={materials.BASE} />
            </group>
            <group name="PYRAMID" position={[6.78, -8.828, -14.347]}>
              <group name="Voronoi_Fracture" position={[0, -113.215, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                <group name="Pyramid_fracturepart1" position={[-55.37, -19.148, 72.246]} rotation={[-1.355, 0, 0]} scale={0.753}>
                  <mesh name="Pyramid_fracturepart1_BASE_0" geometry={nodes.Pyramid_fracturepart1_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart10" position={[-73.217, -81.951, 63.081]} rotation={[-1.307, 0, 0]} scale={0.697}>
                  <mesh name="Pyramid_fracturepart10_BASE_0" geometry={nodes.Pyramid_fracturepart10_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart100" position={[69.888, 47.175, 129.777]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart100_BASE_0" geometry={nodes.Pyramid_fracturepart100_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart101" position={[59.801, 42.492, 26.791]} rotation={[-1.114, 0, 0]} scale={0.477}>
                  <mesh name="Pyramid_fracturepart101_BASE_0" geometry={nodes.Pyramid_fracturepart101_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart102" position={[-123.462, -94.995, 108.299]} rotation={[-1.546, 0, 0]} scale={0.972}>
                  <mesh name="Pyramid_fracturepart102_BASE_0" geometry={nodes.Pyramid_fracturepart102_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart103" position={[134.891, 43.753, 136.781]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart103_BASE_0" geometry={nodes.Pyramid_fracturepart103_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart104" position={[2.022, 43.031, 21.702]} rotation={[-1.087, 0, 0]} scale={0.446}>
                  <mesh name="Pyramid_fracturepart104_BASE_0" geometry={nodes.Pyramid_fracturepart104_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart105" position={[-37.331, 52.337, 80.443]} rotation={[-1.399, 0, 0]} scale={0.803}>
                  <mesh name="Pyramid_fracturepart105_BASE_0" geometry={nodes.Pyramid_fracturepart105_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart106" position={[-18.206, 35.805, -31.915]} rotation={[-0.803, 0, 0]} scale={0.12}>
                  <mesh name="Pyramid_fracturepart106_BASE_0" geometry={nodes.Pyramid_fracturepart106_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart107" position={[-83.496, 26.973, 89.798]} rotation={[-1.448, 0, 0]} scale={0.86}>
                  <mesh name="Pyramid_fracturepart107_BASE_0" geometry={nodes.Pyramid_fracturepart107_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart108" position={[72.714, -66.747, 47.383]} rotation={[-1.223, 0, 0]} scale={0.602}>
                  <mesh name="Pyramid_fracturepart108_BASE_0" geometry={nodes.Pyramid_fracturepart108_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart109" position={[116.556, 41.223, 108.272]} rotation={[-1.546, 0, 0]} scale={0.972}>
                  <mesh name="Pyramid_fracturepart109_BASE_0" geometry={nodes.Pyramid_fracturepart109_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart11" position={[-51.057, 56.222, 122.053]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart11_BASE_0" geometry={nodes.Pyramid_fracturepart11_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart110" position={[13.344, -27.623, 107.091]} rotation={[-1.54, 0, 0]} scale={0.965}>
                  <mesh name="Pyramid_fracturepart110_BASE_0" geometry={nodes.Pyramid_fracturepart110_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart111" position={[72.393, -35.273, 11.035]} rotation={[-1.031, 0, 0]} scale={0.381}>
                  <mesh name="Pyramid_fracturepart111_BASE_0" geometry={nodes.Pyramid_fracturepart111_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart112" position={[75.33, -75.086, 12.963]} rotation={[-1.041, 0, 0]} scale={0.393}>
                  <mesh name="Pyramid_fracturepart112_BASE_0" geometry={nodes.Pyramid_fracturepart112_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart113" position={[38.463, 62.477, 57.787]} rotation={[-1.279, 0, 0]} scale={0.665}>
                  <mesh name="Pyramid_fracturepart113_BASE_0" geometry={nodes.Pyramid_fracturepart113_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart114" position={[53.199, -56.749, 32.326]} rotation={[-1.144, 0, 0]} scale={0.51}>
                  <mesh name="Pyramid_fracturepart114_BASE_0" geometry={nodes.Pyramid_fracturepart114_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart115" position={[-109.308, 57.414, 80.369]} rotation={[-1.398, 0, 0]} scale={0.802}>
                  <mesh name="Pyramid_fracturepart115_BASE_0" geometry={nodes.Pyramid_fracturepart115_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart116" position={[-43.437, 98.711, 64.19]} rotation={[-1.313, 0, 0]} scale={0.704}>
                  <mesh name="Pyramid_fracturepart116_BASE_0" geometry={nodes.Pyramid_fracturepart116_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart117" position={[-115.075, 28.404, 110.968]} rotation={[-1.561, 0, 0]} scale={0.988}>
                  <mesh name="Pyramid_fracturepart117_BASE_0" geometry={nodes.Pyramid_fracturepart117_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart118" position={[30.012, -35.585, -0.578]} rotation={[-0.969, 0, 0]} scale={0.311}>
                  <mesh name="Pyramid_fracturepart118_BASE_0" geometry={nodes.Pyramid_fracturepart118_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart119" position={[118.996, -26.587, 125.838]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart119_BASE_0" geometry={nodes.Pyramid_fracturepart119_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart12" position={[-19.023, 9.389, 115.052]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart12_BASE_0" geometry={nodes.Pyramid_fracturepart12_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart120" position={[80.612, -4.731, 107.116]} rotation={[-1.54, 0, 0]} scale={0.965}>
                  <mesh name="Pyramid_fracturepart120_BASE_0" geometry={nodes.Pyramid_fracturepart120_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart121" position={[58.857, -60.89, 131.244]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart121_BASE_0" geometry={nodes.Pyramid_fracturepart121_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart122" position={[-49.637, -0.057, -47.746]} rotation={[-0.719, 0, 0]} scale={0.024}>
                  <mesh name="Pyramid_fracturepart122_BASE_0" geometry={nodes.Pyramid_fracturepart122_BASE_0.geometry} material={materials.BASE} position={[0, 0, 0]} />
                </group>
                <group name="Pyramid_fracturepart123" position={[3.976, 23.652, -98.294]} scale={0}>
                  <mesh name="Pyramid_fracturepart123_BASE_0" geometry={nodes.Pyramid_fracturepart123_BASE_0.geometry} material={materials.BASE} position={[0, 1140204, -21462150]} scale={0.999} />
                </group>
                <group name="Pyramid_fracturepart124" position={[-25.397, -101.572, 75.409]} rotation={[-1.372, 0, 0]} scale={0.772}>
                  <mesh name="Pyramid_fracturepart124_BASE_0" geometry={nodes.Pyramid_fracturepart124_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart125" position={[-18.991, 27.914, 42.343]} rotation={[-1.197, 0, 0]} scale={0.571}>
                  <mesh name="Pyramid_fracturepart125_BASE_0" geometry={nodes.Pyramid_fracturepart125_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart126" position={[-46.012, -11.633, 124.202]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart126_BASE_0" geometry={nodes.Pyramid_fracturepart126_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart127" position={[-1.69, -83.118, 62.758]} rotation={[-1.305, 0, 0]} scale={0.695}>
                  <mesh name="Pyramid_fracturepart127_BASE_0" geometry={nodes.Pyramid_fracturepart127_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart128" position={[-66.927, -65.102, 11.045]} rotation={[-1.031, 0, 0]} scale={0.381}>
                  <mesh name="Pyramid_fracturepart128_BASE_0" geometry={nodes.Pyramid_fracturepart128_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart129" position={[16.067, -99.597, 94.266]} rotation={[-1.472, 0, 0]} scale={0.887}>
                  <mesh name="Pyramid_fracturepart129_BASE_0" geometry={nodes.Pyramid_fracturepart129_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart13" position={[21.58, 88.468, 31.755]} rotation={[-1.141, 0, 0]} scale={0.507}>
                  <mesh name="Pyramid_fracturepart13_BASE_0" geometry={nodes.Pyramid_fracturepart13_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart130" position={[50.366, 56.941, 101.866]} rotation={[-1.512, 0, 0]} scale={0.933}>
                  <mesh name="Pyramid_fracturepart130_BASE_0" geometry={nodes.Pyramid_fracturepart130_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart131" position={[-122.907, -112.257, 121.303]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart131_BASE_0" geometry={nodes.Pyramid_fracturepart131_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart132" position={[33.884, -80.808, 27.995]} rotation={[-1.121, 0, 0]} scale={0.484}>
                  <mesh name="Pyramid_fracturepart132_BASE_0" geometry={nodes.Pyramid_fracturepart132_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart133" position={[-17.647, -102.416, 125.841]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart133_BASE_0" geometry={nodes.Pyramid_fracturepart133_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart134" position={[20.425, 2.356, -69.901]} scale={0}>
                  <mesh name="Pyramid_fracturepart134_BASE_0" geometry={nodes.Pyramid_fracturepart134_BASE_0.geometry} material={materials.BASE} position={[0, -8964136, -24322028]} scale={0.999} />
                </group>
                <group name="Pyramid_fracturepart135" position={[-0.248, 115.812, 120.593]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart135_BASE_0" geometry={nodes.Pyramid_fracturepart135_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart136" position={[5.575, -4.88, 10.547]} rotation={[-1.028, 0, 0]} scale={0.378}>
                  <mesh name="Pyramid_fracturepart136_BASE_0" geometry={nodes.Pyramid_fracturepart136_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart137" position={[-109.629, 92.287, 96.686]} rotation={[-1.485, 0, 0]} scale={0.901}>
                  <mesh name="Pyramid_fracturepart137_BASE_0" geometry={nodes.Pyramid_fracturepart137_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart138" position={[6.942, 66.477, 51.612]} rotation={[-1.246, 0, 0]} scale={0.628}>
                  <mesh name="Pyramid_fracturepart138_BASE_0" geometry={nodes.Pyramid_fracturepart138_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart139" position={[-56.509, 6.668, 2.197]} rotation={[-0.984, 0, 0]} scale={0.327}>
                  <mesh name="Pyramid_fracturepart139_BASE_0" geometry={nodes.Pyramid_fracturepart139_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart14" position={[16.947, 53.528, 124.241]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart14_BASE_0" geometry={nodes.Pyramid_fracturepart14_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart140" position={[-53.249, 34.261, 11.553]} rotation={[-1.033, 0, 0]} scale={0.384}>
                  <mesh name="Pyramid_fracturepart140_BASE_0" geometry={nodes.Pyramid_fracturepart140_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart141" position={[36.163, -120.428, 107.204]} rotation={[-1.541, 0, 0]} scale={0.965}>
                  <mesh name="Pyramid_fracturepart141_BASE_0" geometry={nodes.Pyramid_fracturepart141_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart142" position={[99.657, 35.443, 99.522]} rotation={[-1.5, 0, 0]} scale={0.919}>
                  <mesh name="Pyramid_fracturepart142_BASE_0" geometry={nodes.Pyramid_fracturepart142_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart143" position={[70.205, -131.269, 127.226]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart143_BASE_0" geometry={nodes.Pyramid_fracturepart143_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart144" position={[66.623, 19.629, 10.011]} rotation={[-1.025, 0, 0]} scale={0.375}>
                  <mesh name="Pyramid_fracturepart144_BASE_0" geometry={nodes.Pyramid_fracturepart144_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart145" position={[-92.022, -111.475, 125.029]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart145_BASE_0" geometry={nodes.Pyramid_fracturepart145_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart146" position={[-0.177, 82.618, 69.615]} rotation={[-1.341, 0, 0]} scale={0.737}>
                  <mesh name="Pyramid_fracturepart146_BASE_0" geometry={nodes.Pyramid_fracturepart146_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart147" position={[-27.589, -30.905, -18.209]} rotation={[-0.876, 0, 0]} scale={0.203}>
                  <mesh name="Pyramid_fracturepart147_BASE_0" geometry={nodes.Pyramid_fracturepart147_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart148" position={[59.298, 25.727, -12.742]} rotation={[-0.905, 0, 0]} scale={0.237}>
                  <mesh name="Pyramid_fracturepart148_BASE_0" geometry={nodes.Pyramid_fracturepart148_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart149" position={[21.329, -41.634, 73.742]} rotation={[-1.363, 0, 0]} scale={0.762}>
                  <mesh name="Pyramid_fracturepart149_BASE_0" geometry={nodes.Pyramid_fracturepart149_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart15" position={[-6.856, -82.665, 28.956]} rotation={[-1.126, 0, 0]} scale={0.49}>
                  <mesh name="Pyramid_fracturepart15_BASE_0" geometry={nodes.Pyramid_fracturepart15_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart150" position={[19.518, 9.06, -27.176]} rotation={[-0.828, 0, 0]} scale={0.149}>
                  <mesh name="Pyramid_fracturepart150_BASE_0" geometry={nodes.Pyramid_fracturepart150_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart151" position={[41.087, 14.949, 96.44]} rotation={[-1.484, 0, 0]} scale={0.9}>
                  <mesh name="Pyramid_fracturepart151_BASE_0" geometry={nodes.Pyramid_fracturepart151_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart152" position={[-87.623, 73.582, 30.322]} rotation={[-1.133, 0, 0]} scale={0.498}>
                  <mesh name="Pyramid_fracturepart152_BASE_0" geometry={nodes.Pyramid_fracturepart152_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart153" position={[27.516, -12.113, -94.039]} scale={0}>
                  <mesh name="Pyramid_fracturepart153_BASE_0" geometry={nodes.Pyramid_fracturepart153_BASE_0.geometry} material={materials.BASE} position={[0, -5722688, -9487767]} scale={0.999} />
                </group>
                <group name="Pyramid_fracturepart154" position={[116.808, -54.689, 128.091]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart154_BASE_0" geometry={nodes.Pyramid_fracturepart154_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart155" position={[79.114, 85.216, 77.238]} rotation={[-1.382, 0, 0]} scale={0.783}>
                  <mesh name="Pyramid_fracturepart155_BASE_0" geometry={nodes.Pyramid_fracturepart155_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart156" position={[-43.088, 14.234, 31.77]} rotation={[-1.141, 0, 0]} scale={0.507}>
                  <mesh name="Pyramid_fracturepart156_BASE_0" geometry={nodes.Pyramid_fracturepart156_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart157" position={[-17.081, 102.897, 100.887]} rotation={[-1.507, 0, 0]} scale={0.927}>
                  <mesh name="Pyramid_fracturepart157_BASE_0" geometry={nodes.Pyramid_fracturepart157_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart158" position={[33.112, 39.361, 19.807]} rotation={[-1.077, 0, 0]} scale={0.434}>
                  <mesh name="Pyramid_fracturepart158_BASE_0" geometry={nodes.Pyramid_fracturepart158_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart159" position={[79.735, -21.783, 51.962]} rotation={[-1.248, 0, 0]} scale={0.63}>
                  <mesh name="Pyramid_fracturepart159_BASE_0" geometry={nodes.Pyramid_fracturepart159_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart16" position={[-50.786, 39.131, -42.697]} rotation={[-0.746, 0, 0]} scale={0.055}>
                  <mesh name="Pyramid_fracturepart16_BASE_0" geometry={nodes.Pyramid_fracturepart16_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart17" position={[-33.277, 70.046, 92.756]} rotation={[-1.464, 0, 0]} scale={0.878}>
                  <mesh name="Pyramid_fracturepart17_BASE_0" geometry={nodes.Pyramid_fracturepart17_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart18" position={[-99.079, 8.746, 129.442]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart18_BASE_0" geometry={nodes.Pyramid_fracturepart18_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart19" position={[37.484, 11.034, 50.827]} rotation={[-1.242, 0, 0]} scale={0.623}>
                  <mesh name="Pyramid_fracturepart19_BASE_0" geometry={nodes.Pyramid_fracturepart19_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart2" position={[-53.568, 75.356, 34.48]} rotation={[-1.155, 0, 0]} scale={0.524}>
                  <mesh name="Pyramid_fracturepart2_BASE_0" geometry={nodes.Pyramid_fracturepart2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart20" position={[-75.617, 20.583, 57.16]} rotation={[-1.275, 0, 0]} scale={0.661}>
                  <mesh name="Pyramid_fracturepart20_BASE_0" geometry={nodes.Pyramid_fracturepart20_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart21" position={[-127.917, 119.387, 125.011]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart21_BASE_0" geometry={nodes.Pyramid_fracturepart21_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart22" position={[91.199, 112.995, 98.653]} rotation={[-1.495, 0, 0]} scale={0.913}>
                  <mesh name="Pyramid_fracturepart22_BASE_0" geometry={nodes.Pyramid_fracturepart22_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart23" position={[-97.567, -62.926, 83.932]} rotation={[-1.417, 0, 0]} scale={0.824}>
                  <mesh name="Pyramid_fracturepart23_BASE_0" geometry={nodes.Pyramid_fracturepart23_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart24" position={[-98.624, -29.339, 76.937]} rotation={[-1.38, 0, 0]} scale={0.782}>
                  <mesh name="Pyramid_fracturepart24_BASE_0" geometry={nodes.Pyramid_fracturepart24_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart25" position={[43.418, 6.829, -22.415]} rotation={[-0.853, 0, 0]} scale={0.178}>
                  <mesh name="Pyramid_fracturepart25_BASE_0" geometry={nodes.Pyramid_fracturepart25_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart26" position={[-25.475, 58.114, 134.09]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart26_BASE_0" geometry={nodes.Pyramid_fracturepart26_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart27" position={[29.327, 40.827, -30.148]} rotation={[-0.812, 0, 0]} scale={0.131}>
                  <mesh name="Pyramid_fracturepart27_BASE_0" geometry={nodes.Pyramid_fracturepart27_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart28" position={[-22.693, -59.544, 128.309]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart28_BASE_0" geometry={nodes.Pyramid_fracturepart28_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart29" position={[-42.244, 17.109, -41.423]} rotation={[-0.753, 0, 0]} scale={0.062}>
                  <mesh name="Pyramid_fracturepart29_BASE_0" geometry={nodes.Pyramid_fracturepart29_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart3" position={[-81.064, -21.659, 14.486]} rotation={[-1.049, 0, 0]} scale={0.402}>
                  <mesh name="Pyramid_fracturepart3_BASE_0" geometry={nodes.Pyramid_fracturepart3_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart30" position={[65.957, 92.552, 121.147]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart30_BASE_0" geometry={nodes.Pyramid_fracturepart30_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart31" position={[-89.491, 79.922, 75.705]} rotation={[-1.374, 0, 0]} scale={0.774}>
                  <mesh name="Pyramid_fracturepart31_BASE_0" geometry={nodes.Pyramid_fracturepart31_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart32" position={[14.618, -42.623, -48.501]} rotation={[-0.715, 0, 0]} scale={0.019}>
                  <mesh name="Pyramid_fracturepart32_BASE_0" geometry={nodes.Pyramid_fracturepart32_BASE_0.geometry} material={materials.BASE} position={[0, 0, 0.001]} />
                </group>
                <group name="Pyramid_fracturepart33" position={[73.006, -55.844, 105.534]} rotation={[-1.532, 0, 0]} scale={0.955}>
                  <mesh name="Pyramid_fracturepart33_BASE_0" geometry={nodes.Pyramid_fracturepart33_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart34" position={[-71.166, 121.851, 127.671]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart34_BASE_0" geometry={nodes.Pyramid_fracturepart34_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart35" position={[112.549, 91.804, 86.594]} rotation={[-1.431, 0, 0]} scale={0.84}>
                  <mesh name="Pyramid_fracturepart35_BASE_0" geometry={nodes.Pyramid_fracturepart35_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart36" position={[90.111, 125.071, 125.115]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart36_BASE_0" geometry={nodes.Pyramid_fracturepart36_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart37" position={[52.063, -0.318, 135.209]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart37_BASE_0" geometry={nodes.Pyramid_fracturepart37_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart38" position={[9.652, -32.323, 133.458]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart38_BASE_0" geometry={nodes.Pyramid_fracturepart38_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart39" position={[89.116, -90.106, 78.417]} rotation={[-1.388, 0, 0]} scale={0.79}>
                  <mesh name="Pyramid_fracturepart39_BASE_0" geometry={nodes.Pyramid_fracturepart39_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart4" position={[47.959, 58.488, 38.426]} rotation={[-1.176, 0, 0]} scale={0.548}>
                  <mesh name="Pyramid_fracturepart4_BASE_0" geometry={nodes.Pyramid_fracturepart4_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart40" position={[108.548, 4.279, 90.111]} rotation={[-1.45, 0, 0]} scale={0.862}>
                  <mesh name="Pyramid_fracturepart40_BASE_0" geometry={nodes.Pyramid_fracturepart40_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart41" position={[93.554, -109.403, 130.92]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart41_BASE_0" geometry={nodes.Pyramid_fracturepart41_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart42" position={[-42.14, -54.973, -0.852]} rotation={[-0.968, 0, 0]} scale={0.309}>
                  <mesh name="Pyramid_fracturepart42_BASE_0" geometry={nodes.Pyramid_fracturepart42_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart43" position={[-77.931, -53.782, 133.95]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart43_BASE_0" geometry={nodes.Pyramid_fracturepart43_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart44" position={[111.139, 41.273, 138.334]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart44_BASE_0" geometry={nodes.Pyramid_fracturepart44_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart45" position={[29.077, 49.511, -12.25]} rotation={[-0.907, 0, 0]} scale={0.24}>
                  <mesh name="Pyramid_fracturepart45_BASE_0" geometry={nodes.Pyramid_fracturepart45_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart46" position={[49.758, -26.262, -32.451]} rotation={[-0.8, 0, 0]} scale={0.117}>
                  <mesh name="Pyramid_fracturepart46_BASE_0" geometry={nodes.Pyramid_fracturepart46_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart47" position={[-94.208, -102.448, 77.386]} rotation={[-1.383, 0, 0]} scale={0.784}>
                  <mesh name="Pyramid_fracturepart47_BASE_0" geometry={nodes.Pyramid_fracturepart47_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart48" position={[29.448, -46.945, 30.13]} rotation={[-1.132, 0, 0]} scale={0.497}>
                  <mesh name="Pyramid_fracturepart48_BASE_0" geometry={nodes.Pyramid_fracturepart48_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart49" position={[3.821, -19.174, -94.922]} scale={0}>
                  <mesh name="Pyramid_fracturepart49_BASE_0" geometry={nodes.Pyramid_fracturepart49_BASE_0.geometry} material={materials.BASE} position={[0, 2784584, -27213256]} scale={0.999} />
                </group>
                <group name="Pyramid_fracturepart5" position={[-10.73, -43.99, 44.671]} rotation={[-1.209, 0, 0]} scale={0.585}>
                  <mesh name="Pyramid_fracturepart5_BASE_0" geometry={nodes.Pyramid_fracturepart5_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart50" position={[83.244, 37.903, 55.014]} rotation={[-1.264, 0, 0]} scale={0.648}>
                  <mesh name="Pyramid_fracturepart50_BASE_0" geometry={nodes.Pyramid_fracturepart50_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart51" position={[3.73, -70.371, 98.363]} rotation={[-1.494, 0, 0]} scale={0.912}>
                  <mesh name="Pyramid_fracturepart51_BASE_0" geometry={nodes.Pyramid_fracturepart51_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart52" position={[-1.555, 68.288, 14.691]} rotation={[-1.05, 0, 0]} scale={0.403}>
                  <mesh name="Pyramid_fracturepart52_BASE_0" geometry={nodes.Pyramid_fracturepart52_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart53" position={[110.731, -41.421, 83.661]} rotation={[-1.416, 0, 0]} scale={0.822}>
                  <mesh name="Pyramid_fracturepart53_BASE_0" geometry={nodes.Pyramid_fracturepart53_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart54" position={[-63.552, 111.062, 113.543]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart54_BASE_0" geometry={nodes.Pyramid_fracturepart54_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart55" position={[-6.707, -25.949, 77.764]} rotation={[-1.385, 0, 0]} scale={0.787}>
                  <mesh name="Pyramid_fracturepart55_BASE_0" geometry={nodes.Pyramid_fracturepart55_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart56" position={[43.914, -89.044, 114.314]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart56_BASE_0" geometry={nodes.Pyramid_fracturepart56_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart57" position={[78.383, 12.832, 29.202]} rotation={[-1.127, 0, 0]} scale={0.491}>
                  <mesh name="Pyramid_fracturepart57_BASE_0" geometry={nodes.Pyramid_fracturepart57_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart58" position={[-40.69, -68.72, 73.461]} rotation={[-1.362, 0, 0]} scale={0.76}>
                  <mesh name="Pyramid_fracturepart58_BASE_0" geometry={nodes.Pyramid_fracturepart58_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart59" position={[-14.229, 20.072, 73.773]} rotation={[-1.363, 0, 0]} scale={0.762}>
                  <mesh name="Pyramid_fracturepart59_BASE_0" geometry={nodes.Pyramid_fracturepart59_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart6" position={[-40.502, -89.786, 124.348]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart6_BASE_0" geometry={nodes.Pyramid_fracturepart6_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart60" position={[-45.88, -107.262, 89.927]} rotation={[-1.449, 0, 0]} scale={0.86}>
                  <mesh name="Pyramid_fracturepart60_BASE_0" geometry={nodes.Pyramid_fracturepart60_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart61" position={[-49.809, -30.079, 92.728]} rotation={[-1.464, 0, 0]} scale={0.877}>
                  <mesh name="Pyramid_fracturepart61_BASE_0" geometry={nodes.Pyramid_fracturepart61_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart62" position={[-112.027, -73.971, 116.926]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart62_BASE_0" geometry={nodes.Pyramid_fracturepart62_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart63" position={[42.04, 45.306, -40.063]} rotation={[-0.76, 0, 0]} scale={0.071}>
                  <mesh name="Pyramid_fracturepart63_BASE_0" geometry={nodes.Pyramid_fracturepart63_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart64" position={[-50.122, 54.562, 137.971]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart64_BASE_0" geometry={nodes.Pyramid_fracturepart64_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart65" position={[-42.447, -128.593, 131.561]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart65_BASE_0" geometry={nodes.Pyramid_fracturepart65_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart66" position={[107.162, -128.462, 138.499]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart66_BASE_0" geometry={nodes.Pyramid_fracturepart66_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart67" position={[-6.426, -49.011, -1.316]} rotation={[-0.965, 0, 0]} scale={0.306}>
                  <mesh name="Pyramid_fracturepart67_BASE_0" geometry={nodes.Pyramid_fracturepart67_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart68" position={[112.168, 90.54, 126.231]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart68_BASE_0" geometry={nodes.Pyramid_fracturepart68_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart69" position={[60.28, -41.413, 116.827]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart69_BASE_0" geometry={nodes.Pyramid_fracturepart69_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart7" position={[-30.358, -19.942, -67.502]} scale={0}>
                  <mesh name="Pyramid_fracturepart7_BASE_0" geometry={nodes.Pyramid_fracturepart7_BASE_0.geometry} material={materials.BASE} position={[2097152, -9286228, -10539064]} scale={0.999} />
                </group>
                <group name="Pyramid_fracturepart70" position={[-112.284, -26.442, 132.126]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart70_BASE_0" geometry={nodes.Pyramid_fracturepart70_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart71" position={[9.934, -24.744, -27.361]} rotation={[-0.827, 0, 0]} scale={0.148}>
                  <mesh name="Pyramid_fracturepart71_BASE_0" geometry={nodes.Pyramid_fracturepart71_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart72" position={[86.145, -93.826, 104.828]} rotation={[-1.528, 0, 0]} scale={0.951}>
                  <mesh name="Pyramid_fracturepart72_BASE_0" geometry={nodes.Pyramid_fracturepart72_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart73" position={[-71.876, 40.257, 132.414]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart73_BASE_0" geometry={nodes.Pyramid_fracturepart73_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart74" position={[-22.975, 76.209, 21.716]} rotation={[-1.087, 0, 0]} scale={0.446}>
                  <mesh name="Pyramid_fracturepart74_BASE_0" geometry={nodes.Pyramid_fracturepart74_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart75" position={[-0.206, 58.951, 90.716]} rotation={[-1.453, 0, 0]} scale={0.865}>
                  <mesh name="Pyramid_fracturepart75_BASE_0" geometry={nodes.Pyramid_fracturepart75_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart76" position={[-47.532, 51.854, -40.322]} rotation={[-0.758, 0, 0]} scale={0.069}>
                  <mesh name="Pyramid_fracturepart76_BASE_0" geometry={nodes.Pyramid_fracturepart76_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart77" position={[81.936, 51.587, 95.459]} rotation={[-1.478, 0, 0]} scale={0.894}>
                  <mesh name="Pyramid_fracturepart77_BASE_0" geometry={nodes.Pyramid_fracturepart77_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart78" position={[48.245, -10.105, 28.623]} rotation={[-1.124, 0, 0]} scale={0.488}>
                  <mesh name="Pyramid_fracturepart78_BASE_0" geometry={nodes.Pyramid_fracturepart78_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart79" position={[-41.652, -24.403, 10.168]} rotation={[-1.026, 0, 0]} scale={0.376}>
                  <mesh name="Pyramid_fracturepart79_BASE_0" geometry={nodes.Pyramid_fracturepart79_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart8" position={[-22.333, -26.132, -47.856]} rotation={[-0.719, 0, 0]} scale={0.023}>
                  <mesh name="Pyramid_fracturepart8_BASE_0" geometry={nodes.Pyramid_fracturepart8_BASE_0.geometry} material={materials.BASE} position={[0, 0, 0]} />
                </group>
                <group name="Pyramid_fracturepart80" position={[-104.103, 92.761, 131.296]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart80_BASE_0" geometry={nodes.Pyramid_fracturepart80_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart81" position={[25.857, -55.215, -19.724]} rotation={[-0.868, 0, 0]} scale={0.194}>
                  <mesh name="Pyramid_fracturepart81_BASE_0" geometry={nodes.Pyramid_fracturepart81_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart82" position={[62.245, 111.854, 90.264]} rotation={[-1.451, 0, 0]} scale={0.862}>
                  <mesh name="Pyramid_fracturepart82_BASE_0" geometry={nodes.Pyramid_fracturepart82_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart83" position={[-123.103, -20.453, 118.418]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart83_BASE_0" geometry={nodes.Pyramid_fracturepart83_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart84" position={[-55.657, -10.479, 136.726]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart84_BASE_0" geometry={nodes.Pyramid_fracturepart84_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart85" position={[-25.428, -5.918, 22.556]} rotation={[-1.092, 0, 0]} scale={0.451}>
                  <mesh name="Pyramid_fracturepart85_BASE_0" geometry={nodes.Pyramid_fracturepart85_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart86" position={[46.772, -12.849, 100.386]} rotation={[-1.504, 0, 0]} scale={0.924}>
                  <mesh name="Pyramid_fracturepart86_BASE_0" geometry={nodes.Pyramid_fracturepart86_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart87" position={[72.582, -41.264, 77.827]} rotation={[-1.385, 0, 0]} scale={0.787}>
                  <mesh name="Pyramid_fracturepart87_BASE_0" geometry={nodes.Pyramid_fracturepart87_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart88" position={[-6.319, 42.03, 127.596]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart88_BASE_0" geometry={nodes.Pyramid_fracturepart88_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart89" position={[17.444, -12.495, -20.285]} rotation={[-0.865, 0, 0]} scale={0.191}>
                  <mesh name="Pyramid_fracturepart89_BASE_0" geometry={nodes.Pyramid_fracturepart89_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart9" position={[60.872, 15.535, 125.385]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart9_BASE_0" geometry={nodes.Pyramid_fracturepart9_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart90" position={[-2.485, -119.097, 104.271]} rotation={[-1.525, 0, 0]} scale={0.948}>
                  <mesh name="Pyramid_fracturepart90_BASE_0" geometry={nodes.Pyramid_fracturepart90_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart91" position={[69.145, 74.634, 18.915]} rotation={[-1.073, 0, 0]} scale={0.429}>
                  <mesh name="Pyramid_fracturepart91_BASE_0" geometry={nodes.Pyramid_fracturepart91_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart92" position={[120.806, -105.956, 121.449]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart92_BASE_0" geometry={nodes.Pyramid_fracturepart92_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart93" position={[66.833, -28.035, 141.418]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart93_BASE_0" geometry={nodes.Pyramid_fracturepart93_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart94" position={[-88.426, -39.764, 117.611]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart94_BASE_0" geometry={nodes.Pyramid_fracturepart94_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart95" position={[-116.23, 49.251, 127.836]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart95_BASE_0" geometry={nodes.Pyramid_fracturepart95_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart96" position={[89.129, -107.022, 113.946]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart96_BASE_0" geometry={nodes.Pyramid_fracturepart96_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart97" position={[118.529, 4.345, 132.223]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart97_BASE_0" geometry={nodes.Pyramid_fracturepart97_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart98" position={[133.732, 117.011, 125.526]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart98_BASE_0" geometry={nodes.Pyramid_fracturepart98_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart99" position={[-70.825, 67.819, 93.326]} rotation={[-1.467, 0, 0]} scale={0.881}>
                  <mesh name="Pyramid_fracturepart99_BASE_0" geometry={nodes.Pyramid_fracturepart99_BASE_0.geometry} material={materials.BASE} />
                </group>
              </group>
            </group>
            <group name="SERVER" position={[-97.146, 27.764, 62.565]} rotation={[0, 0.499, 0]} scale={0.3}>
              <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <group name="Object_221">
                  <primitive object={nodes._rootJoint_1} />
                  <skinnedMesh name="Object_224" geometry={nodes.Object_224.geometry} material={materials.BASE} skeleton={nodes.Object_224.skeleton} />
                </group>
              </group>
            </group>
            <group name="Torus" position={[-113.01, 30.899, -168.905]} rotation={[Math.PI / 2, 0, Math.PI / 4]}>
              <mesh name="Torus_kette_0" geometry={nodes.Torus_kette_0.geometry} material={materials.kette} />
            </group>
          </group>
          <group name="PYRAMID2" position={[-399.743, -40.268, -359.532]} rotation={[-Math.PI / 2, 0, 0]}>
            <group name="FLOATINGISLAND" position={[21.865, 83.957, 52.407]}>
              <group name="Helix" />
            </group>
            <group name="PYRAMID_2" position={[56.935, 67.118, 38.217]} rotation={[Math.PI / 2, 0, 0]}>
              <group name="Voronoi_Fracture_2" position={[0, -57.997, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                <group name="Pyramid_fracturepart10_2" position={[-41.283, -51.499, 37.083]} rotation={[-1.396, 0, 0]} scale={0.8}>
                  <mesh name="Pyramid_fracturepart10_2_BASE_0" geometry={nodes.Pyramid_fracturepart10_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart11_2" position={[-34.479, 31.004, 66.664]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart11_2_BASE_0" geometry={nodes.Pyramid_fracturepart11_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart12_2" position={[-9.777, 3.198, 54.104]} rotation={[-1.507, 0, 0]} scale={0.927}>
                  <mesh name="Pyramid_fracturepart12_2_BASE_0" geometry={nodes.Pyramid_fracturepart12_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart13_2" position={[4.267, 40.432, 20.037]} rotation={[-1.285, 0, 0]} scale={0.672}>
                  <mesh name="Pyramid_fracturepart13_2_BASE_0" geometry={nodes.Pyramid_fracturepart13_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart14_2" position={[8.731, 36.273, 61.949]} rotation={[-1.559, 0, 0]} scale={0.986}>
                  <mesh name="Pyramid_fracturepart14_2_BASE_0" geometry={nodes.Pyramid_fracturepart14_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart15_2" position={[7.525, -48.227, 21.751]} rotation={[-1.296, 0, 0]} scale={0.685}>
                  <mesh name="Pyramid_fracturepart15_2_BASE_0" geometry={nodes.Pyramid_fracturepart15_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart16_2" position={[-21.466, 24.841, -23.161]} rotation={[-1.002, 0, 0]} scale={0.349}>
                  <mesh name="Pyramid_fracturepart16_2_BASE_0" geometry={nodes.Pyramid_fracturepart16_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart17_2" position={[-16.586, 44.753, 47.445]} rotation={[-1.464, 0, 0]} scale={0.878}>
                  <mesh name="Pyramid_fracturepart17_2_BASE_0" geometry={nodes.Pyramid_fracturepart17_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart18_2" position={[-51.782, 5.92, 67.074]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart18_2_BASE_0" geometry={nodes.Pyramid_fracturepart18_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart19_2" position={[25.061, 0.021, 31.706]} rotation={[-1.361, 0, 0]} scale={0.76}>
                  <mesh name="Pyramid_fracturepart19_2_BASE_0" geometry={nodes.Pyramid_fracturepart19_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart1_2" position={[-22.543, -14.091, 43.433]} rotation={[-1.438, 0, 0]} scale={0.847}>
                  <mesh name="Pyramid_fracturepart1_2_BASE_0" geometry={nodes.Pyramid_fracturepart1_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart20_2" position={[-38.255, 11.253, 30.999]} rotation={[-1.356, 0, 0]} scale={0.754}>
                  <mesh name="Pyramid_fracturepart20_2_BASE_0" geometry={nodes.Pyramid_fracturepart20_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart21_2" position={[-69.313, 56.823, 65.254]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart21_2_BASE_0" geometry={nodes.Pyramid_fracturepart21_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart22_2" position={[45.599, 51.47, 49.017]} rotation={[-1.474, 0, 0]} scale={0.889}>
                  <mesh name="Pyramid_fracturepart22_2_BASE_0" geometry={nodes.Pyramid_fracturepart22_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart23_2" position={[-55.864, -50.172, 54.417]} rotation={[-1.509, 0, 0]} scale={0.93}>
                  <mesh name="Pyramid_fracturepart23_2_BASE_0" geometry={nodes.Pyramid_fracturepart23_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart24_2" position={[-56.235, -11.565, 48.204]} rotation={[-1.469, 0, 0]} scale={0.883}>
                  <mesh name="Pyramid_fracturepart24_2_BASE_0" geometry={nodes.Pyramid_fracturepart24_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart25_2" position={[21.944, -9.262, -18.994]} rotation={[-1.03, 0, 0]} scale={0.38}>
                  <mesh name="Pyramid_fracturepart25_2_BASE_0" geometry={nodes.Pyramid_fracturepart25_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart26_2" position={[-11.69, 38.819, 72.198]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart26_2_BASE_0" geometry={nodes.Pyramid_fracturepart26_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart27_2" position={[18.233, 24.61, -24.107]} rotation={[-0.996, 0, 0]} scale={0.342}>
                  <mesh name="Pyramid_fracturepart27_2_BASE_0" geometry={nodes.Pyramid_fracturepart27_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart28_2" position={[-11.592, -32.456, 66.3]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart28_2_BASE_0" geometry={nodes.Pyramid_fracturepart28_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart29_2" position={[-20.911, 8.657, -13.708]} rotation={[-1.064, 0, 0]} scale={0.419}>
                  <mesh name="Pyramid_fracturepart29_2_BASE_0" geometry={nodes.Pyramid_fracturepart29_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart2_2" position={[-28.903, 41.186, 21.855]} rotation={[-1.297, 0, 0]} scale={0.686}>
                  <mesh name="Pyramid_fracturepart2_2_BASE_0" geometry={nodes.Pyramid_fracturepart2_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart30_2" position={[44.798, 49.804, 59.895]} rotation={[-1.545, 0, 0]} scale={0.971}>
                  <mesh name="Pyramid_fracturepart30_2_BASE_0" geometry={nodes.Pyramid_fracturepart30_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart31_2" position={[-54.961, 40.83, 43.893]} rotation={[-1.441, 0, 0]} scale={0.851}>
                  <mesh name="Pyramid_fracturepart31_2_BASE_0" geometry={nodes.Pyramid_fracturepart31_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart32_2" position={[15.208, -21.093, -28.003]} rotation={[-0.971, 0, 0]} scale={0.312}>
                  <mesh name="Pyramid_fracturepart32_2_BASE_0" geometry={nodes.Pyramid_fracturepart32_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart33_2" position={[46.32, -40.156, 45.412]} rotation={[-1.451, 0, 0]} scale={0.862}>
                  <mesh name="Pyramid_fracturepart33_2_BASE_0" geometry={nodes.Pyramid_fracturepart33_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart34_2" position={[-23.235, 61.444, 65.257]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Pyramid_fracturepart34_2_BASE_0" geometry={nodes.Pyramid_fracturepart34_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart3_2" position={[-34.021, -12.55, 6.341]} rotation={[-1.195, 0, 0]} scale={0.57}>
                  <mesh name="Pyramid_fracturepart3_2_BASE_0" geometry={nodes.Pyramid_fracturepart3_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart4_2" position={[24.948, 31.21, 23.523]} rotation={[-1.308, 0, 0]} scale={0.698}>
                  <mesh name="Pyramid_fracturepart4_2_BASE_0" geometry={nodes.Pyramid_fracturepart4_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart5_2" position={[6.137, -19.962, 26.296]} rotation={[-1.326, 0, 0]} scale={0.719}>
                  <mesh name="Pyramid_fracturepart5_2_BASE_0" geometry={nodes.Pyramid_fracturepart5_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart6_2" position={[-17.768, -55.992, 61.468]} rotation={[-1.556, 0, 0]} scale={0.983}>
                  <mesh name="Pyramid_fracturepart6_2_BASE_0" geometry={nodes.Pyramid_fracturepart6_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart7_2" position={[-7.855, -5.694, -49.125]} rotation={[-0.833, 0, 0]} scale={0.154}>
                  <mesh name="Pyramid_fracturepart7_2_BASE_0" geometry={nodes.Pyramid_fracturepart7_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart8_2" position={[-10.922, -15.007, -15.578]} rotation={[-1.052, 0, 0]} scale={0.405}>
                  <mesh name="Pyramid_fracturepart8_2_BASE_0" geometry={nodes.Pyramid_fracturepart8_2_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="Pyramid_fracturepart9_2" position={[44.871, 2.429, 60.53]} rotation={[-1.549, 0, 0]} scale={0.976}>
                  <mesh name="Pyramid_fracturepart9_2_BASE_0" geometry={nodes.Pyramid_fracturepart9_2_BASE_0.geometry} material={materials.BASE} />
                </group>
              </group>
            </group>
            <group name="Torus_1" position={[56.253, -18.013, 56.988]} rotation={[0, 0, -1.083]}>
              <mesh name="Torus_1_kette_0" geometry={nodes.Torus_1_kette_0.geometry} material={materials.kette} />
            </group>
            <group name="WINDMILL" position={[20.582, 83.973, 60.161]} rotation={[0, 0, 1.906]} scale={100}>
              <group name="FLAG" position={[0.329, 0.093, -0.423]} rotation={[Math.PI / 2, 0.251, 0]} scale={0.01}>
                <group name="flag" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="0" geometry={nodes['0'].geometry} material={materials.BASE} morphTargetDictionary={nodes['0'].morphTargetDictionary} morphTargetInfluences={nodes['0'].morphTargetInfluences} />
                </group>
              </group>
              <group name="POLE" position={[0.361, 0.102, -0.042]} rotation={[Math.PI / 2, 0.251, 0]} scale={0.01}>
                <mesh name="POLE_BASE_0" geometry={nodes.POLE_BASE_0.geometry} material={materials.BASE} />
              </group>
              <group name="WindPowerPlant_Body" rotation={[0, 0, -Math.PI / 2]}>
                <group name="BASE" rotation={[0, 0, Math.PI / 2]} scale={0.01}>
                  <mesh name="BASE_BASE_0" geometry={nodes.BASE_BASE_0.geometry} material={materials.BASE} />
                </group>
                <group name="WindPowerPlant_NeckLower" position={[0, 0, 1.079]}>
                  <group name="WindPowerPlant_NeckMedium" position={[0, 0, 1.079]}>
                    <group name="WindPowerPlant_NeckUpper" position={[0, 0, 0.899]} rotation={[0, 0, -0.767]}>
                      <group name="WindPowerPlant_Circle" position={[0.36, 0, 0.899]}>
                        <group name="WindPowerPlant_Wing">
                          <mesh name="WindPowerPlant_Wing_kette_0" geometry={nodes.WindPowerPlant_Wing_kette_0.geometry} material={materials.kette} />
                        </group>
                        <group name="WindPowerPlant_Wing_001" rotation={[-2.094, 0, 0]}>
                          <mesh name="WindPowerPlant_Wing_001_kette_0" geometry={nodes.WindPowerPlant_Wing_001_kette_0.geometry} material={materials.kette} />
                        </group>
                        <group name="WindPowerPlant_Wing_002" rotation={[2.094, 0, 0]}>
                          <mesh name="WindPowerPlant_Wing_002_kette_0" geometry={nodes.WindPowerPlant_Wing_002_kette_0.geometry} material={materials.kette} />
                        </group>
                        <mesh name="WindPowerPlant_Circle_kette_0" geometry={nodes.WindPowerPlant_Circle_kette_0.geometry} material={materials.kette} />
                      </group>
                      <group name="WindPowerPlant_Part">
                        <mesh name="WindPowerPlant_Part_BASE_0" geometry={nodes.WindPowerPlant_Part_BASE_0.geometry} material={materials.BASE} />
                      </group>
                      <mesh name="WindPowerPlant_NeckUpper_BASE_0" geometry={nodes.WindPowerPlant_NeckUpper_BASE_0.geometry} material={materials.BASE} />
                    </group>
                    <mesh name="WindPowerPlant_NeckMedium_BASE_0" geometry={nodes.WindPowerPlant_NeckMedium_BASE_0.geometry} material={materials.BASE} />
                  </group>
                  <mesh name="WindPowerPlant_NeckLower_BASE_0" geometry={nodes.WindPowerPlant_NeckLower_BASE_0.geometry} material={materials.BASE} />
                </group>
                <mesh name="WindPowerPlant_Body_BASE_0" geometry={nodes.WindPowerPlant_Body_BASE_0.geometry} material={materials.BASE} />
              </group>
            </group>
          </group>
          <group name="PYRAMID2_1" position={[-455.106, -65, 137.047]} rotation={[-Math.PI / 2, 0, 0]} />
          <group name="PYRAMID2_2" position={[115.324, 20, -314.057]} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
        <group name="Cloner" position={[-1.177, 0.235, -1.121]} rotation={[-1.633, 0.062, -0.783]} scale={0.01}>
          <group name="Sweep_0" position={[7.057, -3.741, -9.99]} rotation={[-0.251, -1.109, -0.298]}>
            <mesh name="Sweep_0_kette_0" geometry={nodes.Sweep_0_kette_0.geometry} material={materials.kette} />
          </group>
          <group name="Sweep_1" position={[-9.33, -1.02, -42.166]} rotation={[-1.647, 0.286, -1.016]}>
            <mesh name="Sweep_1_kette_0" geometry={nodes.Sweep_1_kette_0.geometry} material={materials.kette} />
          </group>
          <group name="Sweep_10" position={[-269.62, 7.981, -91.838]} rotation={[1.127, 0.527, -0.722]}>
            <mesh name="Sweep_10_kette_0" geometry={nodes.Sweep_10_kette_0.geometry} material={materials.kette} />
          </group>
          <group name="Sweep_11" position={[-291.392, 6.404, -63.02]} rotation={[-1.079, 0.549, 0.877]}>
            <mesh name="Sweep_11_kette_0" geometry={nodes.Sweep_11_kette_0.geometry} material={materials.kette} />
          </group>
          <group name="Sweep_12" position={[-310.159, 3.544, -32.165]} rotation={[-2.248, -0.887, 0.685]}>
            <mesh name="Sweep_12_kette_0" geometry={nodes.Sweep_12_kette_0.geometry} material={materials.kette} />
          </group>
          <group name="Sweep_2" position={[-29.166, 2.201, -72.258]} rotation={[2.414, 0.76, 0.652]}>
            <mesh name="Sweep_2_kette_0" geometry={nodes.Sweep_2_kette_0.geometry} material={materials.kette} />
          </group>
          <group name="Sweep_3" position={[-52.085, 4.298, -100.093]} rotation={[1.062, -0.538, 0.645]}>
            <mesh name="Sweep_3_kette_0" geometry={nodes.Sweep_3_kette_0.geometry} material={materials.kette} />
          </group>
          <group name="Sweep_4" position={[-79, 7.896, -123.857]} rotation={[-0.954, -0.329, -0.56]}>
            <mesh name="Sweep_4_kette_0" geometry={nodes.Sweep_4_kette_0.geometry} material={materials.kette} />
          </group>
          <group name="Sweep_5" position={[-110.329, 9.751, -141.369]} rotation={[-2.652, 0.388, -0.125]}>
            <mesh name="Sweep_5_kette_0" geometry={nodes.Sweep_5_kette_0.geometry} material={materials.kette} />
          </group>
          <group name="Sweep_6" position={[-144.607, 11.743, -151.602]} rotation={[1.796, 0.003, 0.114]}>
            <mesh name="Sweep_6_kette_0" geometry={nodes.Sweep_6_kette_0.geometry} material={materials.kette} />
          </group>
          <group name="Sweep_7" position={[-180.316, 11.815, -148.653]} rotation={[0.024, 0.199, -0.01]}>
            <mesh name="Sweep_7_kette_0" geometry={nodes.Sweep_7_kette_0.geometry} material={materials.kette} />
          </group>
          <group name="Sweep_8" position={[-214.416, 10.942, -137.667]} rotation={[-1.722, -0.114, 0.487]}>
            <mesh name="Sweep_8_kette_0" geometry={nodes.Sweep_8_kette_0.geometry} material={materials.kette} />
          </group>
          <group name="Sweep_9" position={[-243.941, 10.287, -117.052]} rotation={[2.599, -0.606, -0.36]}>
            <mesh name="Sweep_9_kette_0" geometry={nodes.Sweep_9_kette_0.geometry} material={materials.kette} />
          </group>
        </group>
        <group name="Cloner_2" rotation={[-1.658, 0, 0]} scale={0.01}>
          <group name="Sweep_0_2" />
          <group name="Sweep_10_2" position={[-580, 0, 0]} rotation={[Math.PI / 6, 0, 0]} />
          <group name="Sweep_11_2" position={[-638, 0, 0]} rotation={[-1.309, 0, 0]} />
          <group name="Sweep_12_2" position={[-696, 0, 0]} rotation={[-Math.PI, 0, 0]} />
          <group name="Sweep_1_2" position={[-58, 0, 0]} rotation={[-1.833, 0, 0]} />
          <group name="Sweep_2_2" position={[-116, 0, 0]} rotation={[2.618, 0, 0]} />
          <group name="Sweep_3_2" position={[-174, 0, 0]} rotation={[Math.PI / 4, 0, 0]} />
          <group name="Sweep_4_2" position={[-232, 0, 0]} rotation={[-Math.PI / 3, 0, 0]} />
          <group name="Sweep_5_2" position={[-290, 0, 0]} rotation={[-2.88, 0, 0]} />
          <group name="Sweep_6_2" position={[-348, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />
          <group name="Sweep_7_2" position={[-406, 0, 0]} rotation={[-0.262, 0, 0]} />
          <group name="Sweep_8_2" position={[-464, 0, 0]} rotation={[-2.094, 0, 0]} />
          <group name="Sweep_9_2" position={[-522, 0, 0]} rotation={[2.356, 0, 0]} />
        </group>
        <group name="POINTER" position={[-4.487, 5.218, -0.673]} rotation={[-Math.PI, 0.852, -Math.PI]} scale={0.01}>
          <group name="Null" position={[136.074, 93.692, 0]} rotation={[0, 0, 1.92]}>
            <group name="3D" position={[-6.996, -87.45, 0]} rotation={[0, 0, -1.879]}>
              <group name="Text">
                <group name="1">
                  <group name="Click">
                    <group name="c" position={[94.314, 0, 0]}>
                      <mesh name="c_BASE_0" geometry={nodes.c_BASE_0.geometry} material={materials.BASE} />
                    </group>
                    <group name="C">
                      <mesh name="C_BASE_0" geometry={nodes.C_BASE_0.geometry} material={materials.BASE} />
                    </group>
                    <group name="i" position={[73.611, 0, 0]}>
                      <mesh name="i_BASE_0" geometry={nodes.i_BASE_0.geometry} material={materials.BASE} />
                    </group>
                    <group name="k" position={[147.222, 0, 0]}>
                      <mesh name="k_BASE_0" geometry={nodes.k_BASE_0.geometry} material={materials.BASE} />
                    </group>
                    <group name="l" position={[52.908, 0, 0]}>
                      <mesh name="l_BASE_0" geometry={nodes.l_BASE_0.geometry} material={materials.BASE} />
                    </group>
                  </group>
                </group>
              </group>
            </group>
            <group name="Extrude">
              <mesh name="Extrude_BASE_0" geometry={nodes.Extrude_BASE_0.geometry} material={materials.BASE} />
            </group>
          </group>
        </group>
        <mesh name="Icosphere001" geometry={nodes.Icosphere001.geometry} material={nodes.Icosphere001.material} />
        <mesh name="Cylinder_BASE_0" geometry={nodes.Cylinder_BASE_0.geometry} material={materials.BASE} position={[-4.583, 5.046, -0.783]} rotation={[Math.PI / 2, 0, -2.29]} scale={0.01} />
        <mesh name="Node1" geometry={nodes.Node1.geometry} material={materials.x1} position={[-1.27, 3.401, 3.071]} rotation={[1.569, -0.001, -2.412]} scale={0.058} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Computer-transformed.glb')
